sudo: required

services:
  - docker

before_install:
  - docker build -t shalama/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run shalama/react-test npm run test -- --watchAll=false

after_sucess:
  - docker build -t shalama/multi-client ./client
  - docker build -t shalama/multi-server ./server
  - docker build -t shalama/multi-nginx ./nginx
  - docker build -t shalama/multi-worker ./worker
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push shalama/multi-client
  - docker push shalama/multi-server
  - docker push shalama/multi-nginx
  - docker push shalama/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: "eu-central-1"
#   app: "docker-react"
#   env: "Dockerreact-env"
#   bucker_name: "elasticbeanstalk-eu-central-1-265338444229"
#   bucker_path: "docker-react"
#   on:
#     branch: master
#   access_key_id : $access_key_id
#   secret_access_key: $secret_access_key
